### ISSUE TITLE
IOError: [Errno 2] No such file or directory: '/tmp/tmpyLr_Ti_sf2/drumkit.xml'

### ISSUE THREAD

**Issue by gourmate3** [konsumer/hydro2sf2#1]
dude, i love your work.

however when i run 
hydroToSf2 my.h2drumkit
i get the following error.

Traceback (most recent call last):
  File "./hydro2sf2/hydroToSf2", line 243, in <module>
    main(sys.argv)
  File "./hydro2sf2/hydroToSf2", line 238, in main
    hydrogenToSf(drumkitDir,sf2,stereo,tempDir)
  File "./hydro2sf2/hydroToSf2", line 128, in hydrogenToSf
    hydroData = parseHydrogenDrumkit(path.join(drumkitDir,'drumkit.xml'))
  File "./hydro2sf2/hydroToSf2", line 19, in parseHydrogenDrumkit
    doc=xml.dom.minidom.parse(filename)
  File "/usr/lib/python2.7/xml/dom/minidom.py", line 1918, in parse
    return expatbuilder.parse(file)
  File "/usr/lib/python2.7/xml/dom/expatbuilder.py", line 922, in parse
    fp = open(file, 'rb')
IOError: [Errno 2] No such file or directory: '/tmp/tmpyLr_Ti_sf2/drumkit.xml'

is it my pythons issue?

**Comment by konsumer** [comment]
It's been a really long time since I worked on this (I made it 14 years ago!) It looks like from the error it's not doing the extraction correctly. They may have changed the format of hydrogen files or something, since it's been so long. Does it extract with `tar xvzf my.h2drumkit`? What files are in it? Once you get it extracted (maybe it's a tar.gz or zip, really not sure) You might still be able to re-purpose `hydrogenToSf` to work with the extracted files, if they follow the same format:

```py
def main:
  hydrogenToSf(drumkitDir, sf2='OUT.sf2', stereo=True, tempDir='/tmp')
```

where `drumkitDir` should be the extracted dir where you can find `drumkit.xml`

It may just require a rewrite since it's been so long. I would totally do it a lot differently, now.

**Comment by konsumer** [comment]
I did a quick check of the first downloadable drumkit (''The Black Pearl 1.0")

and I got this for file-list (after a `tar xz`):

```
Cowbell-Hardest.wav            PearlTomFloor-Med.wav
Cowbell-Hard.wav               PearlTomFloor-Softest.wav
Cowbell-Med.wav                PearlTomFloor-Soft.wav
Cowbell-Softest.wav            SabianCrashFlink-Hardest.wav
Cowbell-Soft.wav               SabianCrashFlink-Hard.wav
drumkit.xml                    SabianCrashFlink-Med.wav
HandClap.wav                   SabianCrashFlink-Softest.wav
PaisteBell-Hardest.wav         SabianCrashFlink-Soft.wav
PaisteBell-Hard.wav            SabianCrash-Hardest.wav
PaisteBell-Med.wav             SabianCrash-Hard.wav
PaisteBell-Softest.wav         SabianCrash-Med.wav
PaisteBell-Soft.wav            SabianCrash-Softest.wav
PaisteRideFlink-Hardest.wav    SabianCrash-Soft.wav
PaisteRideFlink-Hard.wav       SabianHatChoke-Hardest.wav
PaisteRideFlink-Med.wav        SabianHatChoke-Hard.wav
PaisteRideFlink-Softest.wav    SabianHatChoke-Med.wav
PaisteRideFlink-Soft.wav       SabianHatChoke-Softest.wav
PaisteRide-Hardest.wav         SabianHatChoke-Soft.wav
PaisteRide-Hard.wav            SabianHatClosed-Hardest.wav
PaisteRide-Med.wav             SabianHatClosed-Hard.wav
PaisteRide-Softest.wav         SabianHatClosed-Med.wav
PaisteRide-Soft.wav            SabianHatClosed-Softest.wav
PearlKick-Hardest.wav          SabianHatClosed-Soft.wav
PearlKick-Hard.wav             SabianHatOpen-Hardest.wav
PearlKick-Med.wav              SabianHatOpen-Hard.wav
PearlKick-Softest.wav          SabianHatOpen-Med.wav
PearlKick-Soft.wav             SabianHatOpen-Softest.wav
PearlSideStick-Hardest.wav     SabianHatOpen-Soft.wav
PearlSideStick-Hard.wav        SabianHatPedal-Hardest.wav
PearlSideStick-Med.wav         SabianHatPedal-Hard.wav
PearlSideStick-Softest.wav     SabianHatPedal-Med.wav
PearlSideStick-Soft.wav        SabianHatPedal-Softest.wav
PearlSnare-Hardest.wav         SabianHatPedal-Soft.wav
PearlSnare-Hard.wav            SabianHatSemiOpen-Hardest.wav
PearlSnare-Med.wav             SabianHatSemiOpen-Hard.wav
PearlSnareRimshot-Hardest.wav  SabianHatSemiOpen-Med.wav
PearlSnareRimshot-Hard.wav     SabianHatSemiOpen-Softest.wav
PearlSnareRimshot-Med.wav      SabianHatSemiOpen-Soft.wav
PearlSnareRimshot-Softest.wav  SabianHatSwish-Hardest.wav
PearlSnareRimshot-Soft.wav     SabianHatSwish-Hard.wav
PearlSnare-Softest.wav         SabianHatSwish-Med.wav
PearlSnare-Soft.wav            SabianHatSwish-Softest.wav
PearlTom1-Hardest.wav          SabianHatSwish-Soft.wav
PearlTom1-Hard.wav             ZildjianSplashChoke-Hardest.wav
PearlTom1-Med.wav              ZildjianSplashChoke-Hard.wav
PearlTom1-Softest.wav          ZildjianSplashChoke-Med.wav
PearlTom1-Soft.wav             ZildjianSplashChoke-Softest.wav
PearlTom2-Hardest.wav          ZildjianSplashChoke-Soft.wav
PearlTom2-Hard.wav             ZildjianSplash-Hardest.wav
PearlTom2-Med.wav              ZildjianSplash-Hard.wav
PearlTom2-Softest.wav          ZildjianSplash-Med.wav
PearlTom2-Soft.wav             ZildjianSplash-Softest.wav
PearlTomFloor-Hardest.wav      ZildjianSplash-Soft.wav
PearlTomFloor-Hard.wav
```

So, at least on the surface, it appears to have same format (tar + gzip, drumkit.xml at root references relative audio file paths.)


It might be some prob with my arg-parsing mess (I think back then I didn't know about `argparse` or it seemed too complicated or something.)

so try this, in the top-level of the repo, with the `my.h2drumkit` in the same dir:

```sh
mkdir kit
cd kit
tar xvzf ../my.h2drumkit
```

Then edit `hydroToSf2`, remove `main` function and add this:

```py
def main:
  hydrogenToSf('./kit', sf2='my.sf2', stereo=True, tempDir='/tmp')
```

Then run it:

```sh
./hydroToSf2
```

This should get you where you need to be, but let me know how it goes or if you need more help.

**Comment by konsumer** [comment]
I do mostly js dev now, so I am wondering if maybe I should just rewrite it in node. I think it's possible to do all the file conversion with native modules, so it would mean no other system-dependencies other than nodejs.

I originally wrote it (log says 2009, but that was just when I put it on github, I think maybe it was before 2006, even) because I had a soundcard that could do soundfonts directly, and my computer was too slow to run hydrogen for live shows. I would convert to SF2, then at a show upload it to my soundcard, then send my soundcard midi from the extremely light [seq24](http://www.filter24.org/seq24/) for a very low-resource drum machine. I would combine this with other midi sequences in seq24 & live keyboard input for a complete band-setup. I haven't had such a low-end machine for a very long time, but I still kinda miss the SF2-native capabilities.

Thanks for the new-year reminder of old cool code!

**Comment by glenpike** [comment]
Just ran into this problem, you can extract the file (like above) and run hydro2sf2 on the directory, e.g.

```
tar -xzf my_kit.h2drumkit
./hydro2sf2 my_kit my_sf2_kit
```

**Comment by konsumer** [comment]
@glenpike Yep, I discovered same. I think I need to fix up the old python code, something about extracting it seems broken. I couldn't find a good modern way to make a SF2 file, especially with another language, so I'm really not sure how to go about updating it.

**Comment by glenpike** [comment]
> @glenpike Yep, I discovered same. I think I need to fix up the old python code, something about extracting it seems broken. I couldn't find a good modern way to make a SF2 file, especially with another language, so I'm really not sure how to go about updating it.

Hi, thanks for the reply.  If you are interested, it might be easier to create an SFZ file - https://sfzformat.com/ - this supports WAV and FLAC, is just a folder + vaguely XML-type format for each sample.  Might be easier to translate from Hydrogen format?

**Comment by konsumer** [comment]
Yeh, I like SFZ, and it's super-easy to work with. Originally this project was specifically for making SF2 (so my creative labs card could use the soundfont) maybe just another project to does that should be made & recommended.

**Comment by konsumer** [comment]
I'd also really be into porting a better SF2 lib (like libgig that supports a ton more formats) to wasm. wasm has a ton of host-options, so you can compile it once and use it in a million other languages (see wasmer.)
